### ISSUE TITLE
If the message is blank, a blank line is sent to chat

### ISSUE THREAD

**Issue by BinaryCrafter** [NickTheDev/GraveChest#2]
Would it be possible to have the plugin detect the value of `getString("Chest.Message")`([here](https://github.com/NickTheDev/GraveChest/blob/master/src/main/java/net/nikdev/gravechest/listeners/PlayerDeath.java#L91)) being empty, and then in that instance not send a blank line to chat?

**Comment by NickTheDev** [comment]
Of course! I will rework the logic of the death message when I get a chance as well.
